name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions | env - ${{ inputs.target-env}}
on:
  workflow_dispatch:
    inputs:
      target-env:
        description: "Target environment"
        required: true
        type: choice
        options:
          - "dev"
          - "prod"
env:
  working-directory: "17-custom-actions/react-app"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ env.working-directory }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: "20.x"
          working-directory: ${{ env.working-directory }}
      - name: Run Tests
        run: npm run test
      - name: Building
        run: npm run build
